pipeline:
  name: Terrafom-CI
  identifier: TerrafomCI
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Terraform-Init
        identifier: TerraformInit
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: aws_workspace
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
        tags: {}
